version: '3.7'

services:
  web:
    build: .
    command: python /src/manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/src 
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    environment:
      # - "POSTGRES_HOST_AUTH_METHOD=trust"
      POSTGRES_PASSWORD: password
    image: postgres:11